#!/bin/sh

if [ ! -e void-packages/xbps-src ]; then
    git submodule update --init
fi

for pkg in srcpkgs/*; do
    tgt=void-packages/${pkg}
    rm -rf ${tgt}
    cp -r ${pkg} ${tgt}
done

exec void-packages/xbps-src -m $(pwd)/masterdir -H $(pwd)/hostdir "$@"
